name: sulteng_data
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shimmer: ^2.0.0
  google_fonts: ^2.3.1
  get_storage: ^2.0.3
  carousel_slider: ^4.0.0
  extended_image: ^6.0.2+1
  flutter_spinkit: ^5.1.0
  lottie: ^1.2.2
  font_awesome_flutter: ^10.0.0
  line_icons: ^2.0.1
  iconsax: ^0.0.8
  eva_icons_flutter: ^3.1.0
  infinite_scroll_pagination: ^3.1.0
  flutter_cupertino_datetime_picker: ^3.0.0
  permission_handler: ^9.2.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.2.2
  intl: ^0.17.0
  clipboard: ^0.1.3
  keyboard_attachable: ^2.1.0
  flutter_native_splash: 2.1.1
  flutter_launcher_icons: 0.9.2
  flutter_config: ^2.0.0
  flutter_downloader: ^1.7.3
  carousel_with_indicator: 
    path: ../packages/carousel_with_indicator
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/locales/
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/images/bps_logo.png
  android: true
  ios: true
  fullscreen: false

flutter_icons: 
  image_path: assets/images/bps_logo.png
  android: launcher_icon
  ios: true

